# Site settings
title: Dr. Rangeel Singh Raina
email: contact@rangeelraina.com
description: >- 
  Professional portfolio of Dr. Rangeel Singh Raina, MBBS, M.D. (Pharmacology),
  Principal and Professor at Government Medical College, Haridwar, specializing in
  Pharmacology, Patient Safety, and Drug Information. Member of Executive Council of
  National Association of Pharmacology and Therapeutics.
baseurl: "" # empty baseurl for custom domain
url: "https://drrangeel.kubefoundation.com" # your custom domain
# Social profiles
twitter_username: 
github_username:  
linkedin_username: rangeel-singh-041999a5
research_gate: profile/Rangeel_Singh
google_scholar: 
orcid: 
pubmed: 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  publications:
    output: true
    permalink: /:collection/:name

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md